### ISSUE TITLE
Improve inline gallery mode on mobile

### ISSUE THREAD

**Issue by freiserg** [dimsemenov/PhotoSwipe#1050]
I use photoswipe as inline gallery (non-modal model).

I've removed prevetDefault() in [gestures.js](https://github.com/dimsemenov/PhotoSwipe/blob/master/src/js/gestures.js#L412) 

Also I've added styles:

```css
/* TODO: Fix vertical scroll in android */
.pswp,
.pswp__container,
.pswp__zoom-wrap {
    -ms-touch-action: pan-y !important;
    touch-action: pan-y !important;
}
```
`touch-action: none;` doesn't allow to scroll in android.

And I use these settings:

```
closeOnScroll: false,
maxSpreadZoom: 1,
modal: false,
closeOnVerticalDrag: false
```
I tested it in IOS 8,9; Android 4.0.3, 4.2.2, 5.2 and mobile windows 8. It woks.

Maybe, it will help improve non-modal mode.
