### ISSUE TITLE
Change size of left and right arrow

### ISSUE THREAD

**Issue by jucuegas** [dimsemenov/PhotoSwipe#1073]
Hello,
I need to increase the size of the left and right arrows but not how to do it.
I searched through the documentation but I see nothing.
In the picture below, I've marked arrows want to resize.
![screenshot_20160215203013](https://cloud.githubusercontent.com/assets/17257991/13058356/fc0bd436-d422-11e5-85e8-9115fe9908b0.png)
Regards

**Comment by dimsemenov** [comment]
Styling of all controls is applied from skin CSS file

https://github.com/dimsemenov/PhotoSwipe/tree/master/dist/default-skin

**Comment by jucuegas** [comment]
Dimsemenov Many thanks,
I was using a remote skin and did not know there was a png file.

thanks again, I could fix it

**Comment by mavajih** [comment]
@jucuegas @dimsemenov Did you able to change the arrow size ? if yes, please suggest.

**Comment by puremana** [comment]
You could double the size of them using the same png assets doing
```css
html body .pswp__ui .pswp__button--arrow--left:before, html body .pswp__ui .pswp__button--arrow--right:before {
  background-size: 528px 176px;
  height:60px;
  width:64px;
  top:24px;
  left:4px;
}

.pswp__button--arrow--left::before {
  background-position:-276px -88px !important;  
}

.pswp__button--arrow--right::before {
  background-position:-188px -88px !important;
}
```
or by using [zoom](https://developer.mozilla.org/en-US/docs/Web/CSS/zoom)
