### ISSUE TITLE
Bower default-skin location

### ISSUE THREAD

**Issue by johnhearfield** [dimsemenov/PhotoSwipe#1287]
When running bower + gulp, it outputs the default-skin.png to **/dist/images/default-skin.png**. In the code it references **/dist/styles/default-skin.png** and such throws an error.

The minified css/sass is at **dist/styles/main.css**

Is is possible to override the background url for default-skin.png?

**Comment by johnhearfield** [comment]
I can just override it in my css like this

```css
.pswp__button:not(.pswp__button--arrow--left):not(.pswp__button--arrow--right),
.pswp__button--arrow--left:before,
.pswp__button--arrow--right:before {
  background-image: url(../images/default-skin.png);
}
```
