### ISSUE TITLE
V5-Beta  Is attribute data-cropped="true" correctly working?

### ISSUE THREAD

**Issue by acwolff** [dimsemenov/PhotoSwipe#1781]
[This album](https://www.andrewolff.nl/Test_Photopswipe_V5/PhotoSwipe-5-beta/PSP-cropping/) containes fixed-size thumbnails which are all cropped., so I added attribute data-cropped="true" to all thumbnails like the 7th panoramic image:

    <a  href="slides/080515_01_W2_Kioni_Anogi_360PF1.jpg" data-pswp-width="13548" data-pswp-height="1920" id="6"
    data-cropped="true" data-caption='idem via expanded view'>
     <div class="box" style = "width:120px">
       <img   src="thumbs/080515_01_W2_Kioni_Anogi_360PF1.jpg" width="120" height="80" alt="2008-05-15" title="2008-05-15"  /><br>
     </div>
    </a>

I don't think that the addition lof this attribute eads to a smoothly zoom-out transition, try-it-yourself.

Do I something wrongly?  
Or is the difference in aspect ratio too extreme?

[This album](https://www.andrewolff.nl/Test_Photopswipe_V5/PSP5/) has been made with the same images but now with a thumbnails page made with the Justified Gallery, only images 6 and 7 are cropped and do have the data-cropped="true"  attribute, but I am not impressed by the results off this added attribute.

**Comment by dimsemenov** [comment]
The aspect ratio of thumbnail image itself must match the large image, you crop it via CSS (either via `background-size:cover`, or `object-fit: cover;`).

**Comment by acwolff** [comment]
Well I don’t think my thumbnails are cropped via CSS, it is done with a [JAVA ConstrainRatioFilter](https://jalbum.net/forum/thread.jspa?messageID=331788&#331788), so that explains why ir does not work. 
i will investigate the methos you indicated. Could you give a link to some example code?

Thanks for your quick response!

**Comment by BilouMaster** [comment]
You can see cropped thumbnails on [my gallery](https://biloumaster.fr/gallery/), thumbnails are cropped with this kind of CSS:

```css
.gallery {
    display: flex;
    flex-wrap: wrap;
}
.gallery:after {
    content: '';
    flex-grow: 5;
}
.thumb {
    margin: 2px;
    flex-grow: 1;
    max-height: 250px;
    overflow: hidden;
}
.thumb > img {
    height: 100%;
    width: 100%;
    object-fit: cover;
}
```
With the scheme:
```html
<div class="gallery">
    <a class="thumb" ... >
        <img ... >
    </a>
    <a class="thumb" ... >
        <img ... >
    </a>
    <a class="thumb" ... >
        <img ... >
    </a>
</div>
```
