### ISSUE TITLE
V5 Beta: How to hide the buttons only?

### ISSUE THREAD

**Issue by acwolff** [dimsemenov/PhotoSwipe#1810]
While a slideshow is running, I hide now the buttons with code:

         pswp.template.classList.toggle('pswp--ui-visible');         

However that hides the caption as well.

I tried this to hide only the buttons with this code:

    function showBtns(show) {
        const x = document.querySelector('.pswp__button');
        if (show) {x.style.visibility = "visible";}
        else {x.style.visibility = "hidden";};
    }

But that does not work.

With which code can I hide the buttons in such a way that the caption is still visible?

**Comment by dimsemenov** [comment]
PhotoSwipe controls visibility of controls from CSS file, feel free to adjust or override it.

If you want your own class, you can do something like:

```
new PhotoSwipeLightbox({
   // ...
   mainClass:  `pswp--buttons-visible`
});
```



and in CSS

```css
.pswp .pswp__button {
  opacity: 0;
  transition: opacity 0.3s linear;
} 
.pswp--buttons-visible .pswp__button {
  opacity: 1;
} 
```

and then toggle it somehow:

```js
pswp.template.classList.toggle('pswp--buttons-visible');    
```
