### ISSUE TITLE
iPhone SE : navigation arrows not showing

### ISSUE THREAD

**Issue by AbsurdePhoton** [dimsemenov/PhotoSwipe#1923]
Hi, on an iphone SE 2020 (the only one I got at home so I can't test others), the navigation buttons don't show up. The rest of the ui is fine, though.

The same setup works great on androids and major browsers, just this tiny bug.

I tried to set the z-index of arrow buttons but no, it's not the solution... any other idea ?

**Comment by dimsemenov** [comment]
Hi, the arrows are hidden on purpose, you can control this via CSS.

```css
/* hide arrows on touch screens */
.pswp--touch .pswp__button--arrow {
  visibility: hidden;
}

/* show arrows only after mouse was used */
.pswp--has_mouse .pswp__button--arrow {
  visibility: visible;
}
```
