### ISSUE TITLE
uilayer shows black box over picture in PhoneGap / jQMobile

### ISSUE THREAD

**Issue by crizCraig** [dimsemenov/PhotoSwipe#477]
Adding `opacity: 0` to the folowing

``` css
/* UILayer */
div.ps-uilayer {
    opacity: 0;
    cursor: pointer;
}
```

fixes the problem.

It looks like opacity gets set in the JS, but for some reason this wasn't happening in the app. This seems like a good solution since the uilayer never really needs to be opaque.
